name: Snap build & test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-snap:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Snapcraft
        run: sudo snap install snapcraft --classic

      - name: Pre-install core22
        run: sudo snap install core22 --channel=latest/stable

      - name: Build Snap (Destructive Mode)
        run: |
          snapcraft --destructive-mode
          ls -lh *.snap

      - name: Upload Snap Artifact
        uses: actions/upload-artifact@main
        with:
          name: asimov-cli-snap
          path: "*.snap"

      - name: Check Built Snap File
        run: ls -lh *.snap

      - name: Install Snap Package
        run: sudo snap install --dangerous --devmode *.snap || (echo "Snap installation failed!" && exit 1)

      - name: List Installed Snaps
        run: snap list

      - name: Check Available Commands
        run: snap info asimov-cli

      - name: Verify Installation (asimov --version)
        run: snap run asimov-cli.asimov --version

      # Extract the version from snapcraft.yaml
      - name: Extract Version from snapcraft.yaml
        id: get_version
        run: echo "SNAP_VERSION=$(grep '^version:' snapcraft.yaml | awk '{print $2}' | tr -d "'")" >> $GITHUB_ENV

      # Create a Git tag based on the extracted version
      - name: Create Git Tag
        run: |
          git tag v${{ env.SNAP_VERSION }}
          git push origin v${{ env.SNAP_VERSION }}

      # Create GitHub Release and attach the .snap file
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ env.SNAP_VERSION }}"
          name: "Asimov CLI Release ${{ env.SNAP_VERSION }}"
          body: "Automated release for Asimov CLI Snap build version ${{ env.SNAP_VERSION }}."
          draft: false
          prerelease: true
          files: "*.snap"
