name: Snap build & test

on:
  push:

jobs:
  build-snap:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Snapcraft
        run: sudo snap install snapcraft --classic

      - name: Pre-install core22
        run: sudo snap install core22 --channel=latest/stable

      - name: Build Snap (Destructive Mode)
        run: |
          snapcraft --destructive-mode
          ls -lh *.snap

      - name: Upload Snap Artifact
        uses: actions/upload-artifact@main
        with:
          name: asimov-cli-snap
          path: "*.snap"

      - name: Check Built Snap File
        run: ls -lh *.snap

      - name: Install Snap Package
        run: sudo snap install --dangerous --devmode *.snap || (echo "Snap installation failed!" && exit 1)

      - name: List Installed Snaps
        run: snap list

      - name: Verify Installation (asimov --version)
        run: snap run asimov --version
