name: Build and Test Snap

on:
  push:
#    branches: [ "main" ]
#  pull_request:

jobs:
  build-snap:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Snapcraft
        run: sudo snap install snapcraft --classic

      - name: Pre-install core22
        run: sudo snap install core22 --channel=latest/stable

      - name: Build Snap (Destructive Mode)
        run: snapcraft --destructive-mode

      - name: Upload Snap Artifact
        uses: actions/upload-artifact@main
        with:
          name: asimov-cli-snap
          path: "*.snap"

  test-snap:
    needs: build-snap
    runs-on: ubuntu-latest
    steps:
      - name: Download Snap Artifact
        uses: actions/download-artifact@main
        with:
          name: asimov-cli-snap

      - name: Install and Test Snap
        run: |
          sudo snap install --dangerous ./*.snap
          asimov --version
